/** Target languages for SG16 Translate — SG16 AI handles any name in the list. */
export const POPULAR_LANGUAGES = [
  'Malay',
  'English',
  'Arabic',
  'Chinese (Simplified)',
  'Chinese (Traditional)',
  'Tamil',
  'Hindi',
  'Indonesian',
  'Thai',
  'Vietnamese',
  'Tagalog',
  'Japanese',
  'Korean',
] as const;

export const ALL_LANGUAGES = [
  'Afrikaans',
  'Albanian',
  'Amharic',
  'Arabic',
  'Armenian',
  'Azerbaijani',
  'Basque',
  'Belarusian',
  'Bengali',
  'Bosnian',
  'Bulgarian',
  'Burmese',
  'Catalan',
  'Cebuano',
  'Chinese (Simplified)',
  'Chinese (Traditional)',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'English',
  'Estonian',
  'Filipino',
  'Finnish',
  'French',
  'Galician',
  'Georgian',
  'German',
  'Greek',
  'Gujarati',
  'Hausa',
  'Hebrew',
  'Hindi',
  'Hungarian',
  'Icelandic',
  'Igbo',
  'Indonesian',
  'Irish',
  'Italian',
  'Japanese',
  'Javanese',
  'Kannada',
  'Kazakh',
  'Khmer',
  'Korean',
  'Kurdish',
  'Lao',
  'Latvian',
  'Lithuanian',
  'Macedonian',
  'Malay',
  'Malayalam',
  'Maltese',
  'Marathi',
  'Mongolian',
  'Nepali',
  'Norwegian',
  'Pashto',
  'Persian (Farsi)',
  'Polish',
  'Portuguese',
  'Portuguese (Brazil)',
  'Punjabi',
  'Romanian',
  'Russian',
  'Serbian',
  'Sinhala',
  'Slovak',
  'Slovenian',
  'Somali',
  'Spanish',
  'Spanish (Latin America)',
  'Swahili',
  'Swedish',
  'Tagalog',
  'Tamil',
  'Telugu',
  'Thai',
  'Turkish',
  'Ukrainian',
  'Urdu',
  'Uzbek',
  'Vietnamese',
  'Welsh',
  'Xhosa',
  'Yiddish',
  'Yoruba',
  'Zulu',
] as const;

/** Unique sorted list for the language picker (popular first, then A–Z). */
export function getTranslateLanguageOptions(): string[] {
  const popular = [...POPULAR_LANGUAGES];
  const rest = [...new Set(ALL_LANGUAGES)]
    .filter((lang) => !popular.includes(lang as (typeof POPULAR_LANGUAGES)[number]))
    .sort((a, b) => a.localeCompare(b));
  return [...popular, ...rest];
}

export function filterLanguages(query: string, languages: string[]): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return languages;
  return languages.filter((lang) => lang.toLowerCase().includes(q));
}
