import { SG16_BRAND } from '../core/branding';
import type { HelpSection } from '../core/types';

export type LegalSection = Exclude<HelpSection, never>;

export const LEGAL_SECTIONS: { id: LegalSection; title: string; body: string[] }[] = [
  {
    id: 'overview',
    title: 'Getting Started',
    body: [
      'Open Shield Home and choose one of five shields: AI Chat, Coding Hub, Health, Student, or Market.',
      'Each shield is a separate workspace — coding, health, and student conversations are not mixed together.',
      'AI Chat Shield is free after Google sign-in. Other shields require All Access when billing is active.',
      'Sign in with Google only — we never ask for your password on this site.',
      'Use History and Settings from the sidebar inside any shield. Help Center covers privacy, terms, and contact.',
    ],
  },
  {
    id: 'privacy',
    title: 'Privacy Policy',
    body: [
      `${SG16_BRAND.name} is operated by ${SG16_BRAND.company}. Official website: ${SG16_BRAND.companyUrl}.`,
      'Sign-in uses Google OAuth only. We never ask for your Google password on this site.',
      'SG16 Secure Processing Room: when you send a message, it goes to sg16engine.com first. SG16 processes your request, applies safety checks, and delivers the answer back to you. You never connect to outside AI apps directly from your browser.',
      'We store your Google account identifier, signup date, subscription status, and coding fair-use counters on our servers to run your account. Chat history stays in your browser on this device unless you clear it in Settings.',
      'We do not store your chat message content in our database. Messages are processed in real time to generate a response, then discarded from our servers.',
      'We do not sell your personal data. You can delete local data anytime from Settings.',
      `Privacy questions: ${SG16_BRAND.contactEmail}`,
    ],
  },
  {
    id: 'terms',
    title: 'Terms of Service',
    body: [
      `By using ${SG16_BRAND.name} you agree to use the platform responsibly and lawfully.`,
      `${SG16_BRAND.name} is a legitimate AI productivity platform by ${SG16_BRAND.company}. It is not a hacking tool and must not be used for illegal activity.`,
      'Do not use SG16 AI to generate harmful, illegal, or abusive content.',
      'Student Shield is designed for educational use — non-educational topics may be redirected to AI Chat.',
      'Health Shield provides general wellness guidance — it is not a doctor and does not diagnose or prescribe.',
      'AI responses may contain errors. Verify important information before acting on it.',
      `${SG16_BRAND.company} may update these terms as the platform evolves. Contact: ${SG16_BRAND.contactEmail}`,
    ],
  },
  {
    id: 'license',
    title: 'License & Sovereign Brain',
    body: [
      `${SG16_BRAND.name} runs on a self-hosted sovereign AI brain: ${SG16_BRAND.sovereignBrain} under the ${SG16_BRAND.sovereignLicense} license.`,
      'The brain is operated on SG16-owned infrastructure (sovereign VPS). Responses are generated by SG16 AI — not routed through a third-party ChatGPT or OpenAI gateway when sovereign mode is active.',
      `Apache 2.0 applies to the Mistral model weights and usage terms published by the model licensor. SG16 application code and branding are © ${SG16_BRAND.company}.`,
      'Cloudflare (DNS, CDN, WAF, Pages) protects sg16engine.com at the edge. Cloudflare now offers official AI services — AI Gateway, Workers AI, Agents SDK, and AI Search — with bring-your-own-model support for AI assistants. SG16 implements full sovereign mode: self-hosted Mistral on SG16 infrastructure, not a rented ChatGPT wrapper.',
      'Zero-Data Trace Policy: chat message content is processed in real time to produce a reply and is not stored in our database. Account metadata (Google ID, plan tier, fair-use counters) is kept only to run your account.',
      'Coding Shield and Platform Shield use open-source security tools (Semgrep, Gitleaks, Trivy, Lynis, and others) on our infrastructure — defensive scans only.',
      `Technical ownership: API served from ${SG16_BRAND.publicUrl} via SG16 Secure Room. Check /health for brain status.`,
      `Questions: ${SG16_BRAND.contactEmail}`,
    ],
  },
  {
    id: 'contact',
    title: 'Contact Us',
    body: [
      `Company: ${SG16_BRAND.company}`,
      `Registered office: ${SG16_BRAND.registeredAddress}`,
      SG16_BRAND.jurisdiction,
      `Product: ${SG16_BRAND.name}`,
      `Website: ${SG16_BRAND.publicUrl}`,
      `Corporate site: ${SG16_BRAND.companyUrl}`,
      `Email: ${SG16_BRAND.contactEmail}`,
      'For All Access subscription, billing, or platform questions, email us with your account email.',
      'We typically respond within 1–2 business days.',
    ],
  },
];

export function legalSectionByPath(pathname: string): LegalSection | null {
  const normalized = pathname.replace(/\/+$/, '') || '/';
  if (normalized === '/privacy') return 'privacy';
  if (normalized === '/terms') return 'terms';
  if (normalized === '/contact') return 'contact';
  if (normalized === '/license') return 'license';
  if (normalized === '/help') return 'overview';
  return null;
}

export function isPublicLegalPath(pathname: string): boolean {
  return legalSectionByPath(pathname) != null;
}
